const ORGANIZATION_TYPES = {
    NGO: "NGO",
    COMPANY: "COMPANY",
    COLLEGE: "COLLEGE",
    CLUB: "CLUB",
    GOVERNMENT: "GOVERNMENT",
    COMMUNITY: "COMMUNITY",
    OTHER: "OTHER",
};

const ORGANIZATION_REQUEST_STATUS = {
    PENDING: "PENDING",
    UNDER_REVIEW: "UNDER_REVIEW",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    NEEDS_MORE_INFO: "NEEDS_MORE_INFO",
};

module.exports = {
    ORGANIZATION_TYPES,
    ORGANIZATION_REQUEST_STATUS,
};