const USER_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    SUSPENDED: "SUSPENDED",
};

const ORGANIZATION_STATUS = {
    PENDING: "PENDING",
    UNDER_REVIEW: "UNDER_REVIEW",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
};

const EVENT_STATUS = {
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
};

module.exports = {
    USER_STATUS,
    ORGANIZATION_STATUS,
    EVENT_STATUS,
};